name: Python Web App CI/CD

on:
  push:
    branches:
      - main  # You can specify your main branch here

jobs:
  ecs-ci-cd:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your desired AWS region


    - name: Create Docker Build and Upload to ECR 
      run: | 
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n6d1u1n6
        docker build -t flask-calc-demo .
        docker tag flask-calc-demo:latest public.ecr.aws/s3c4l2m0/flask-calc-demo:latest
        docker push public.ecr.aws/s3c4l2m0/flask-calc-demo:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster docker-training-python-web-cluster --service docker-training-python-service --force-new-deployment
